apiVersion: v1 
kind: ConfigMap
metadata:
  name: catalogue 
  Labels:
    name: catalogue
    namespace: roboshop-dev
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop-dev
  labels:
    name: catalogue
    namespace: roboshop-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalogue
      tier: backend
      env: dev
  template:
    metadata:
      Labels: 
        service: catalogue
        tier: backend
        env: dev
    spec:
      containers:
        name: catalogue
        image: anuragbojja/catalogue:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 1
          periodSeconds: 5
          
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          failureThreshold: 3
          periodSeconds: 10

---
apiVersion: v1 
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    service: catalogue
    tier: backend
    env: dev
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080